sudo: required
services:
  - docker

before_install:
  - docker build -t chriselias/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chriselias/docker-react npm run test -- --coverage
