sudo: required
services:
  - docker

before_install:
  - docker build -t chriselias/docker-react -f Dockerfile.dev .
# CI=true
script:
  - docker CI=true run chriselias/docker-react npm run test -- --coverage
